### ISSUE TITLE
[Bug]: Saved search saving error

### ISSUE THREAD

**Issue by Se7en-IT** [pimcore/advanced-object-search#245] opened 2023-09-19 08:27 UTC
### Expected behavior

Saved search save complete.

### Actual behavior

Error on "save" saved search.
<img width="988" alt="Screenshot 2023-09-19 alle 10 22 03" src="https://github.com/pimcore/advanced-object-search/assets/1436757/95b2c161-fd50-4909-b771-91333bb745d5">

### Steps to reproduce

Click on button "save" on Saved Search tab

**Comment by Se7en-IT** [comment] 2023-09-19 08:33
I solved it by editing the following line of code in the file src/Model/SavedSearch/Dao.php line 67:

from

`Helper::upsert($this->db, self::TABLE_NAME, $data, $this->getPrimaryKey(self::TABLE_NAME));`

to

`Helper::upsert($this->db, self::TABLE_NAME, $data, $this->getPrimaryKey(self::TABLE_NAME), false);`

**Comment by dvesh3** [comment] 2023-09-26 09:10
@Se7en-IT sorry, not able to reproduce. could you please try with latest version `5.0.4`?

**Comment by webdev-dp** [comment] 2023-09-28 08:56
@Se7en-IT thank you for opening the issue. we are having the same issue on our side. 
we we tried with version `5.0.4` and `5.0.2`

**Comment by webdev-dp** [comment] 2023-10-04 12:09
@dvesh3 any updates on this Issue ?

**Comment by dvesh3** [comment] 2023-10-04 12:17
Same status, not able to reproduce on our end.

**Comment by webdev-dp** [comment] 2023-10-04 13:12
> Same status, not able to reproduce on our end.

which pimcore and advanced-object-search version do you have on your end ? can i get access to test ?

**Comment by dvesh3** [comment] 2023-10-04 13:16
I'm using the latest version 5.0.4. you can try on https://demo.pimcore.com/admin creds: superuser/enterprisedemo

**Comment by webdev-dp** [comment] 2023-10-04 13:27
> I'm using the latest version 5.0.4. you can try on https://demo.pimcore.com/admin creds: superuser/enterprisedemo

im using pimcore 10.6 and latest version 5.0.4 and i still get the issue

**Comment by dvesh3** [comment] 2023-10-04 14:14
@webdev-dp sorry, I don't have 10.6 instance running. could you please debug why the double quoting happens? maybe we can pass the `quote: false` with version if else check e.g. `\Pimcore\Version::getMajorVersion() >= 11`

**Comment by webdev-dp** [comment] 2023-10-09 09:37
The issue arises from the `Helper::upsert` function call in the codebase, where we are not explicitly setting the `$quoteIdentifiers` parameter to `false`. You can find the specific line of code [here](https://github.com/pimcore/advanced-object-search/blob/5.x/src/Model/SavedSearch/Dao.php#L67).

Additionally, the problem is exacerbated because the `quoteDataIdentifiers` function is invoked again within the `insert` function, which can lead to unintended behavior. You can review this part of the code [here](https://github.com/pimcore/pimcore/blob/10.6/lib/Db/PimcoreExtensionsTrait.php#L187).

To address this issue, one potential solution is to add a conditional check that examines the Pimcore version. If the version is not 11, you can explicitly set `$quoteIdentifiers` to `false` in the `Helper::upsert` function call, as demonstrated below:

```php
if (\Pimcore\Version::getMajorVersion() !== 11) {
    Helper::upsert($this->db, self::TABLE_NAME, $data, $this->getPrimaryKey(self::TABLE_NAME), false);
}
```

This conditional check ensures that the code behaves correctly on Pimcore versions other than 11.

> @webdev-dp sorry, I don't have 10.6 instance running. could you please debug why the double quoting happens? maybe we can pass the `quote: false` with version if else check e.g. `\Pimcore\Version::getMajorVersion() >= 11`

**Comment by webdev-dp** [comment] 2023-10-11 07:47
@dvesh3 , any update ?

**Comment by dvesh3** [comment] 2023-10-11 07:58
The suggestion looks fine to me so we should pass different params based on the `getMajorVersion()`. Can you provide a PR?

**Comment by webdev-dp** [comment] 2023-10-11 13:05
@dvesh3 i created a PR https://github.com/pimcore/advanced-object-search/pull/247

**Comment by webdev-dp** [comment] 2023-10-13 12:40
new PR https://github.com/pimcore/advanced-object-search/pull/249

**Comment by aryaantony92** [comment] 2023-10-16 09:41
Fixed by https://github.com/pimcore/advanced-object-search/pull/249

**Closed as completed by aryaantony92** 2023-10-16 09:41 UTC
Labels: Bug

**Comment by webdev-dp** [comment] 2023-10-30 09:28
@dvesh3 when is the new release  5.0.5 ?
