### ISSUE TITLE
Mapping Issues after Pimcore-Upgrade

### ISSUE THREAD

**Issue by ascheererEberbach** [pimcore/advanced-object-search#126] opened 2021-07-01 14:25 UTC
Hello dear Pimcore team, 

we just upgraded a client project to Pimcore 6.9.4. This also changed the code of the Advanced ObjectSearch-plugin. 
We are using Advanced ObjectSearch 3.3.1 at the moment and the Elasticsearch-Server has the version 6.8.10. 
The pimcore upgrade changed the Elasticsearch-PHP-Client to 7.13.0.

After struggeling with many problems, we have one problem with one object left: 

http://localhost/project_customer/_mapping?include_type_name=false
["{"error":{"root_cause":[{"type":"parse_exception","reason":"properties must be a map type"}],"type":"parse_exception","reason":"properties must be a map type"},"status":400}"]

We suspect, that the Elasticsearch-client has problems with our Elasticsearch installation. Perhaps we need more configuration. 

The customer-class has \CustomerManagementFrameworkBundle\Model\AbstractCustomer\DefaultAbstractUserawareCustomer as parent. Perhaps this is also relevant. 

Can you help us? Is there a version conflict? What can we do? 

Grretings from Germany

Alice

**Comment by fashxp** [comment] 2022-01-11 08:15
did you find a solution for that topic. 
with the given information we have not really an idea what the problem could be.

**Comment by ascheererEberbach** [comment] 2022-01-11 11:00
Hi @fashxp,

thanks for your answer.
We still don't have a solution to this problem. we just catch the exception. 
But I guess, that is having an impact on the search results of the product search, for which we used AOS. 

I found this Java-Code as the source of the error-message [(source):](https://opster.com/es-errors/properties-must-be-a-map-type/) . 

`return true;
  } else if (fieldName.equals("properties")) {
  if (fieldNode instanceof Collection && ((Collection) fieldNode).isEmpty()) {
  // nothing to do here; empty (to support "properties: []" case)
  } else if (!(fieldNode instanceof Map)) {
  throw new ElasticsearchParseException("properties must be a map type");
  } else {
  parseProperties(builder; (Map<string object="">) fieldNode; parserContext);
  }
  return true;
  } else if (fieldName.equals("include_in_all")) {</string>`

There has to be a field named 'properties' which does not include a map. 
But our data-model does not include a field named 'properties', so it has to be included in the AOS-code.

I also tried to find and add the missing map-type or the missing  [title-element](https://stackoverflow.com/questions/34749919/elasticsearch-create-index-with-mappings) as explained in another forum, within the AOS-Code, but I guess, you will find it quicker an without destroying anything. 

Greetings from Germany

Alice

**Comment by fashxp** [comment] 2022-01-11 16:29
did you try to completely rebuild the index from scratch ... by using the `advanced-object-search:re-index` command and then process the index update queue? 

and maybe delete the ES index manually before that.

**Comment by ascheererEberbach** [comment] 2022-01-12 12:27
Hi @fashxp ,

thans for your ideas!
We recreated the index multiple times, without changes in the error message. I don't know, if we deleted the ES index manually on the server, but when I deleted it on my local envirenment today and started a command, which used to produce the error yesterday, I didn't produce the error any more. 
We plan to move the system to a new server next week. So I'll advice my colleague to delete and recreate all indices from scratch during the move and I'll contact you again with the results. 

Greetings from Germay

Alice

**Comment by ascheererEberbach** [comment] 2022-01-21 15:05
Hi @fashxp ,
we just moved our server, installed a completely new Elasticsearch (ES Version 6.8.23 for AOS Version 6.8.23 and Pimcore 6.9.4) and created all the indices from scratch. 
When I called the classes-rebuild-command, the system responded with the same error-message again. 

["{"error":{"root_cause":[{"type":"parse_exception","reason":"properties must be a map type"}],"type":"parse_exception","reason":"properties must be a map type"},"status":400}"]

As a consequence, the changed fields weren't recognized within pimcore (error-message "Unknown method get[[name of the field]]") until I pushed the save-button in the data definition (where the new field was listed).

So, the problem did't fade away. It is still there :(

Greetings from Germany

Alice

**Comment by ascheererEberbach** [comment] 2022-02-24 09:26
Hi @fashxp, 

I had an error in the description of our setting. Our version of AOS is 3.3.1.
So the setup is:

- ES Version 6.8.23 
- AOS Version 3.3.1
- Pimcore 6.9.4

My colleagues found funny workarounds to finish classes-rebuild. But we would really prefer to work normally. 
Can you tell us, which ES and AOS-combination works without problems?

Greetings from Germany

Alice

**Comment by ascheererEberbach** [comment] 2022-03-22 09:07
Hi @fashxp, hi fellow developers,

yesterday I had the time to play around with the versions on my local system a bit. 
I updated AOS to 4.2.5 and Elasticsearch to 7.17.1 and I deleted indices.
After deleting the indices, the commandS "advanced-object-search:update-mapping" and "advanced-object-search:re-index" ran without problems and without errormessages. 
But when I called "php bin/console pimcore:deployment:classes-rebuild -d", I had even more warning-messages than before, like 
this one: 

_"[types removal] Using include_type_name in put mapping requests is deprecated. The parameter will be removed in the next major version.""]_

In the end, classes-rebuild crashed with this exception, which differs only a little bit: 
`In Connection.php line 675:

  {"error":{"root_cause":[{"type":"parse_exception","reason":"properties must be a map type"}],"type":"mapper_parsing
  _exception","reason":"Failed to parse mapping [_doc]: properties must be a map type","caused_by":{"type":"parse_exc
  eption","reason":"properties must be a map type"}},"status":400}
`

When I tried to delete the indices again, Elasticsearch told me, that there aren't any.

Is it possible, that the class-postUpdate-listener uses an older version of the Elasticsearch-PHP-library which produces outdated mapping-code? Or that there is cached mapping-code of older versions hiding anywhere?

What can I do, to ensure a correct mapping-update during "classes-rebuild"? 
Or does it make sense to remove the listener on classes-update?

I would be very happy about any answer!

Desperate greetings from Germany

Alice

**Comment by fashxp** [comment] 2022-04-07 13:20
the warnings about `include_type_name` are 'normal' as we support ES 6 and 7, and this feature is deprecated in ES 7. 

can you share the class definition that causes the problem?

**Comment by danielkestler** [comment] 2022-06-02 12:13
I had the exact same problem. For me, it was having table properties in objects that have numeric keys (0, 1, 2) instead of named keys, which caused the mapping builder to treat it as a numeric array which then results in a wrong mapping configuration.

**Comment by fashxp** [comment] 2022-06-09 09:32
that seems to be the reason for that problem. actually the problem is the key `0`. other numeric values seems to work. 

It seems, that the ES mapping is not working there. to be honest, I don't know an easy solution for that other than generally prefixing the keys in the mapping ... which is done [here](https://github.com/pimcore/advanced-object-search/blob/e74ffaa8266414e97003966d6ae90f03c98e4a3c/src/Filter/FieldDefinitionAdapter/Table.php#L66). 

Workaround would be not use `0` as the key in column configurations of tables. 
Closing for now, we would merge PRs who fix that though...

**Closed as completed by fashxp** 2022-06-09 09:32 UTC
